#!/bin/bash

(( EUID != 0 )) && exec sudo -- "$0" "$@"

domain=${1}
folder=${2}
confPath="/etc/apache2/sites-available/$domain.conf"

if [[ -z $folder ]]; then
    echo "You must specify a folder name under /home/vagrant/Code/"
    echo "e.g. vayesEYS [to be resolved as /home/vagrant/Code/vayesEYS]"
    exit
else
    echo -e "Your Virtual Host is being created... \n"
    echo -e "ServerName   : $domain"
    echo -e "Server Alias : www.$domain"
    echo -e "DocumentRoot is set to /home/vagrant/Code/$folder/public \n"
    sudo touch $confPath
    sudo echo -e "<VirtualHost *:80>" >> $confPath
    sudo echo -e "    ServerAdmin webmaster@localhost" >> $confPath
    sudo echo -e "    ServerName $domain" >> $confPath
    sudo echo -e "    ServerAlias www.$domain" >> $confPath
    sudo echo -e "    DocumentRoot /home/vagrant/Code/$folder/public" >> $confPath
    sudo echo -e "    <Directory /home/vagrant/Code/$folder/public/>" >> $confPath
    sudo echo -e "        Options +Indexes +FollowSymLinks +MultiViews" >> $confPath
    sudo echo -e "            AllowOverride All" >> $confPath
    sudo echo -e "        Require all granted" >> $confPath
    sudo echo -e "    </Directory>" >> $confPath
    sudo echo -e "    ErrorLog \${APACHE_LOG_DIR}/error.log" >> $confPath
    sudo echo -e "    CustomLog \${APACHE_LOG_DIR}/access.log combined" >> $confPath
    sudo echo -e "</VirtualHost>" >> $confPath
    echo -e "$confPath is created \n"

    echo "Enabling $domain ..."
    sudo a2ensite $domain
    echo "Restarting Apache2"
    sudo service apache2 restart
fi
