#!/bin/bash
echo -e "\n@author: Yahya ERTURAN <root@yahyaerturan.com> \n"

(( EUID != 0 )) && exec sudo -- "$0" "$@"

# Go to home directory
cd ~

# Fetch paramaters
domain=${1}
fakeIP=${2}

if [[ -z $fakeIP ]]; then
    echo "192.168.33.10" $domain >> /etc/hosts;
    echo "192.168.33.10" www.$domain >> /etc/hosts;
else
    echo "$fakeIP" $domain >> /etc/hosts;
    echo "$fakeIP" www.$domain >> /etc/hosts;
fi

if grep -q "$domain" /etc/hosts; then
    echo "Your etc/hosts file now containes $domain:";
    echo "***";
    cat /etc/hosts | grep "$domain";
    echo "***";
    echo "$domain is added succesfully!";
else
    echo "An error occured. Adding $domain to etc/hosts is failed!";
fi
